/** Auth and onboarding route paths. */

export const AUTH_ROUTES = {
  home: "/",
  roles: "/roles",
  login: "/auth/login",
  signup: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  dashboard: "/dashboard",
  pendingApproval: "/pending-approval",
  completeProfile: "/complete-profile",
  accessDenied: "/access-denied",
  adminApprovals: "/admin/approvals",
  adminSchools: "/admin/schools",
  adminCohorts: "/admin/cohorts",
  adminPendingEnrollments: "/admin/cohorts/pending-enrollments",
  adminPendingGrading: "/admin/cohorts/pending-grading",
  adminContent: "/admin/content",
  adminSurveys: "/admin/surveys",
  adminDrive: "/admin/drive",
  adminJobs: "/admin/jobs",
  adminShareholderDocs: "/admin/shareholder-docs",
  adminPartnerDocs: "/admin/partner-docs",
  adminPartnerEvents: "/admin/partner-events",
  adminAnalytics: "/admin/analytics",
  adminPoints: "/admin/points",
  adminCredits: "/admin/credits",
} as const;
